### PR TITLE
Implement PARC

### PR DESCRIPTION
**Pull request by jack89roberts**
Recreating #8 after rebase

### CODE REVIEW

**Comment by jack89roberts** [comment]
Status of this:

- Check #20 re thinking about the PCA hyperparmeters.
- I've removed the WIP streaming code to a separate branch, see #17 . This branch currently runs non-streaming in an identical way to Renggli apart from having an extra loop on number of dimensions. Propose we leave this PR as non-streaming PARC and then get streaming working for both Renggli and PARC in a separate PR.
- I've tweaked it so that PARC accepts raw labels (then converts them to one-hot in its main function) rather than one-hot labels. May be something to revisit later but means it accepts the same inputs as Renggli now.

After checking you're ok with the above I'd suggest merging this one and then getting going with #21 .

**Comment by jack89roberts** [comment]
- Set default PCA parameters and add PCA kwargs

**Comment by jack89roberts** [comment]
Could we make `lower_tri_arr` a standalone function (i.e. can stay in parc.py but not nested within parc)? Would be nice to have a simple test for `feature_reduce` and `lower_tri_arr` too ideally. Plus maybe replace the `warnings.warn` with raising an error for now as discussed earlier to have more of a safety belt if we end up using a small model (or large `f` values) in the future?

**Comment by eddableheath** [comment]
`feature_reduce` and `lower_tri_arr` now have tests and the former throws and exception if `f` is too large.

**Pull request merged**
